extends Node

#FAIRE UNE ADDITION DE TOUTE LES DATA ITEMS GENRE POTION + SWORD ET TOUT PUIS FAIRE LE TOTAL AVEC UNE NOUVELLE VARIABLE DATASAVE PUIS SI JAMAIS CEST EGAL A SE NOMBRE ALORS LINVENTAIRE EST PLEIN

var hero = { gold = 500, vie = 1, vieMax = 1, mana = 1, manaMax = 1, puissance = 1, 
endurance = 1, regene_endurance  = 1, attaque = 1, defense = 1  }

var items_posession = { potionVie = 0, potionMana = 0, bague1 = 0, bague2 = 0, bague3 = 0, bottes1 = 0,
bottes2 = 0, bottes3 = 0, bottes4 = 0, bottes5 = 0, bottes6 = 0, bouclier1 = 0, bouclier2 = 0,
bouclier3 = 0, bouclier4 = 0, bouclier5 = 0, bouclier6 = 0, bouclier7 = 0, casque1 = 0, casque2 = 0, 
casque3 = 0, casque4 = 0, casque5 = 0, casque6 = 0, collier1 = 0, collier2 = 0, collier3 = 0, heaume1 = 0,
heaume2 = 0, heaume3 = 0, heaume4 = 0, heaume5 = 0, heaume6 = 0, sword1 = 0, sword2 = 0, sword3 = 0, 
sword4 = 0, sword5 = 0, sword6 = 0, sword7 = 0, sword8 = 0, potionElixir = 0 }

var items_equiper = { bague1 = 0, bague2 = 0, bague3 = 0, bottes1 = 0,
bottes2 = 0, bottes3 = 0, bottes4 = 0, bottes5 = 0, bottes6 = 0, bouclier1 = 0, bouclier2 = 0,
bouclier3 = 0, bouclier4 = 0, bouclier5 = 0, bouclier6 = 0, bouclier7 = 0, casque1 = 0, casque2 = 0, 
casque3 = 0, casque4 = 0, casque5 = 0, casque6 = 0, collier1 = 0, collier2 = 0, collier3 = 0, heaume1 = 0,
heaume2 = 0, heaume3 = 0, heaume4 = 0, heaume5 = 0, heaume6 = 0, sword1 = 0, sword2 = 0, sword3 = 0, 
sword4 = 0, sword5 = 0, sword6 = 0, sword7 = 0, sword8 = 0 }

var addStatVie = 0
var addStatMana = 0
var addStatPuissance = 0
var addStatEndurance = 0
var addStatRegeneEndurance = 0
var addStatAttaque = 0
var addStatDefense = 0

var nbTotalItemsInventaire = 0 
var nbTotalItemsEquipements = 0

const  SAVE_PATH = "user://settings.cfg"

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	load_data()

func load_data():
	var config = ConfigFile.new()
	var err = config.load(SAVE_PATH)
	
	if err != OK:
		print("aucune sauvegarde n'a été détecté")
		save_data()
		return
	
	hero.gold = config.get_value("player", "gold", 500)
	hero.vie = config.get_value("player", "vie", 1)
	hero.vieMax = config.get_value("player", "vie_max", 1)
	hero.mana = config.get_value("player", "mana", 1)
	hero.manaMax = config.get_value("player", "mana_max", 1)
	hero.puissance = config.get_value("player", "puissance", 1)
	hero.endurance = config.get_value("player", "endurance", 1)
	hero.regene_endurance = config.get_value("player", "regene_endurance", 1)
	hero.attaque = config.get_value("player", "attaque", 1)
	hero.defense = config.get_value("player", "defense", 1)
	items_posession.potionVie = config.get_value("items", "potion_vie", 0)
	items_posession.potionMana = config.get_value("items", "potion_mana", 0)
	items_posession.potionElixir = config.get_value("items", "potion_elixir", 0)
	items_posession.bague1 = config.get_value("items", "bague_1", 0)
	items_posession.bague2 = config.get_value("items", "bague_2", 0)
	items_posession.bague3 = config.get_value("items", "bague_3", 0)
	items_posession.bottes1 = config.get_value("items", "bottes_1", 0)
	items_posession.bottes2 = config.get_value("items", "bottes_2", 0)
	items_posession.bottes3 = config.get_value("items", "bottes_3", 0)
	items_posession.bottes4 = config.get_value("items", "bottes_4", 0)
	items_posession.bottes5 = config.get_value("items", "bottes_5", 0)
	items_posession.bottes6 = config.get_value("items", "bottes_6", 0)
	items_posession.bouclier1 = config.get_value("items", "bouclier_1", 0)
	items_posession.bouclier2 = config.get_value("items", "bouclier_2", 0)
	items_posession.bouclier3 = config.get_value("items", "bouclier_3", 0)
	items_posession.bouclier4 = config.get_value("items", "bouclier_4", 0)
	items_posession.bouclier5 = config.get_value("items", "bouclier_5", 0)
	items_posession.bouclier6 = config.get_value("items", "bouclier_6", 0)
	items_posession.bouclier7 = config.get_value("items", "bouclier_7", 0)
	items_posession.casque1 = config.get_value("items", "casque_1", 0)
	items_posession.casque2 = config.get_value("items", "casque_2", 0)
	items_posession.casque3 = config.get_value("items", "casque_3", 0)
	items_posession.casque4 = config.get_value("items", "casque_4", 0)
	items_posession.casque5 = config.get_value("items", "casque_5", 0)
	items_posession.casque6 = config.get_value("items", "casque_6", 0)
	items_posession.collier1 = config.get_value("items", "collier_1", 0)
	items_posession.collier2 = config.get_value("items", "collier_2", 0)
	items_posession.collier3 = config.get_value("items", "collier_3", 0)
	items_posession.heaume1 = config.get_value("items", "heaume_1", 0)
	items_posession.heaume2 = config.get_value("items", "heaume_2", 0)
	items_posession.heaume3 = config.get_value("items", "heaume_3", 0)
	items_posession.heaume4 = config.get_value("items", "heaume_4", 0)
	items_posession.heaume5 = config.get_value("items", "heaume_5", 0)
	items_posession.heaume6 = config.get_value("items", "heaume_6", 0)
	items_posession.sword1 = config.get_value("items", "sword_1", 0)
	items_posession.sword2 = config.get_value("items", "sword_2", 0)
	items_posession.sword3 = config.get_value("items", "sword_3", 0)
	items_posession.sword4 = config.get_value("items", "sword_4", 0)
	items_posession.sword5 = config.get_value("items", "sword_5", 0)
	items_posession.sword6 = config.get_value("items", "sword_6", 0)
	items_posession.sword7 = config.get_value("items", "sword_7", 0)
	items_posession.sword8 = config.get_value("items", "sword_8", 0)
	nbTotalItemsInventaire = config.get_value("inventaire", "all", 0)
	nbTotalItemsEquipements = config.get_value("inventaire", "equipements", 0)
	items_equiper.bague1 = config.get_value("equiper", "bague_1", 0)
	items_equiper.bague2 = config.get_value("equiper", "bague_2", 0)
	items_equiper.bague3 = config.get_value("equiper", "bague_3", 0)
	items_equiper.bottes1 = config.get_value("equiper", "bottes_1", 0)
	items_equiper.bottes2 = config.get_value("equiper", "bottes_2", 0)
	items_equiper.bottes3 = config.get_value("equiper", "bottes_3", 0)
	items_equiper.bottes4 = config.get_value("equiper", "bottes_4", 0)
	items_equiper.bottes5 = config.get_value("equiper", "bottes_5", 0)
	items_equiper.bottes6 = config.get_value("equiper", "bottes_6", 0)
	items_equiper.bouclier1 = config.get_value("equiper", "bouclier_1", 0)
	items_equiper.bouclier2 = config.get_value("equiper", "bouclier_2", 0)
	items_equiper.bouclier3 = config.get_value("equiper", "bouclier_3", 0)
	items_equiper.bouclier4 = config.get_value("equiper", "bouclier_4", 0)
	items_equiper.bouclier5 = config.get_value("equiper", "bouclier_5", 0)
	items_equiper.bouclier6 = config.get_value("equiper", "bouclier_6", 0)
	items_equiper.bouclier7 = config.get_value("equiper", "bouclier_7", 0)
	items_equiper.casque1 = config.get_value("equiper", "casque_1", 0)
	items_equiper.casque2 = config.get_value("equiper", "casque_2", 0)
	items_equiper.casque3 = config.get_value("equiper", "casque_3", 0)
	items_equiper.casque4 = config.get_value("equiper", "casque_4", 0)
	items_equiper.casque5 = config.get_value("equiper", "casque_5", 0)
	items_equiper.casque6 = config.get_value("equiper", "casque_6", 0)
	items_equiper.collier1 = config.get_value("equiper", "collier_1", 0)
	items_equiper.collier2 = config.get_value("equiper", "collier_2", 0)
	items_equiper.collier3 = config.get_value("equiper", "collier_3", 0)
	items_equiper.heaume1 = config.get_value("equiper", "heaume_1", 0)
	items_equiper.heaume2 = config.get_value("equiper", "heaume_2", 0)
	items_equiper.heaume3 = config.get_value("equiper", "heaume_3", 0)
	items_equiper.heaume4 = config.get_value("equiper", "heaume_4", 0)
	items_equiper.heaume5 = config.get_value("equiper", "heaume_5", 0)
	items_equiper.heaume6 = config.get_value("equiper", "heaume_6", 0)
	items_equiper.sword1 = config.get_value("equiper", "sword_1", 0)
	items_equiper.sword2 = config.get_value("equiper", "sword_2", 0)
	items_equiper.sword3 = config.get_value("equiper", "sword_3", 0)
	items_equiper.sword4 = config.get_value("equiper", "sword_4", 0)
	items_equiper.sword5 = config.get_value("equiper", "sword_5", 0)
	items_equiper.sword6 = config.get_value("equiper", "sword_6", 0)
	items_equiper.sword7 = config.get_value("equiper", "sword_7", 0)
	items_equiper.sword8 = config.get_value("equiper", "sword_8", 0)
	addStatVie = config.get_value("stat_bonus", "vie", 0)
	addStatMana = config.get_value("stat_bonus", "mana", 0)
	addStatPuissance = config.get_value("stat_bonus", "puissance", 0)
	addStatEndurance = config.get_value("stat_bonus", "endurance", 0)
	addStatRegeneEndurance = config.get_value("stat_bonus", "regene_endurance", 0)
	addStatAttaque = config.get_value("stat_bonus", "attaque", 0)
	addStatDefense = config.get_value("stat_bonus", "defense", 0)
	

func save_data():
	var config = ConfigFile.new()
	config.set_value("player", "gold", hero.gold)
	config.set_value("player", "vie", hero.vie)
	config.set_value("player", "vie_max", hero.vieMax)
	config.set_value("player", "mana", hero.mana)
	config.set_value("player", "mana_max", hero.manaMax)
	config.set_value("player", "puissance", hero.puissance)
	config.set_value("player", "endurance", hero.endurance)
	config.set_value("player", "regene_endurance", hero.regene_endurance)
	config.set_value("player", "attaque", hero.attaque)
	config.set_value("player", "defense", hero.defense)
	config.set_value("items", "potion_vie", items_posession.potionVie)
	config.set_value("items", "potion_mana", items_posession.potionMana)
	config.set_value("items", "potion_elixir", items_posession.potionElixir)
	config.set_value("items", "bague_1", items_posession.bague1)
	config.set_value("items", "bague_2", items_posession.bague2)
	config.set_value("items", "bague_3", items_posession.bague3)
	config.set_value("items", "bottes_1", items_posession.bottes1)
	config.set_value("items", "bottes_2", items_posession.bottes2)
	config.set_value("items", "bottes_3", items_posession.bottes3)
	config.set_value("items", "bottes_4", items_posession.bottes4)
	config.set_value("items", "bottes_5", items_posession.bottes5)
	config.set_value("items", "bottes_6", items_posession.bottes6)
	config.set_value("items", "bouclier_1", items_posession.bouclier1)
	config.set_value("items", "bouclier_2", items_posession.bouclier2)
	config.set_value("items", "bouclier_3", items_posession.bouclier3)
	config.set_value("items", "bouclier_4", items_posession.bouclier4)
	config.set_value("items", "bouclier_5", items_posession.bouclier5)
	config.set_value("items", "bouclier_6", items_posession.bouclier6)
	config.set_value("items", "bouclier_7", items_posession.bouclier7)
	config.set_value("items", "casque_1", items_posession.casque1)
	config.set_value("items", "casque_2", items_posession.casque2)
	config.set_value("items", "casque_3", items_posession.casque3)
	config.set_value("items", "casque_4", items_posession.casque4)
	config.set_value("items", "casque_5", items_posession.casque5)
	config.set_value("items", "casque_6", items_posession.casque6)
	config.set_value("items", "collier_1", items_posession.collier1)
	config.set_value("items", "collier_2", items_posession.collier2)
	config.set_value("items", "collier_3", items_posession.collier3)
	config.set_value("items", "heaume_1", items_posession.heaume1)
	config.set_value("items", "heaume_2", items_posession.heaume2)
	config.set_value("items", "heaume_3", items_posession.heaume3)
	config.set_value("items", "heaume_4", items_posession.heaume4)
	config.set_value("items", "heaume_5", items_posession.heaume5)
	config.set_value("items", "heaume_6", items_posession.heaume6)
	config.set_value("items", "sword_1", items_posession.sword1)
	config.set_value("items", "sword_2", items_posession.sword2)
	config.set_value("items", "sword_3", items_posession.sword3)
	config.set_value("items", "sword_4", items_posession.sword4)
	config.set_value("items", "sword_5", items_posession.sword5)
	config.set_value("items", "sword_6", items_posession.sword6)
	config.set_value("items", "sword_7", items_posession.sword7)
	config.set_value("items", "sword_8", items_posession.sword8)
	config.set_value("inventaire", "all", nbTotalItemsInventaire)
	config.set_value("inventaire", "equipements", nbTotalItemsEquipements)
	config.set_value("equiper", "bague_1", items_equiper.bague1)
	config.set_value("equiper", "bague_2", items_equiper.bague2)
	config.set_value("equiper", "bague_3", items_equiper.bague3)
	config.set_value("equiper", "bottes_1", items_equiper.bottes1)
	config.set_value("equiper", "bottes_2", items_equiper.bottes2)
	config.set_value("equiper", "bottes_3", items_equiper.bottes3)
	config.set_value("equiper", "bottes_4", items_equiper.bottes4)
	config.set_value("equiper", "bottes_5", items_equiper.bottes5)
	config.set_value("equiper", "bottes_6", items_equiper.bottes6)
	config.set_value("equiper", "bouclier_1", items_equiper.bouclier1)
	config.set_value("equiper", "bouclier_2", items_equiper.bouclier2)
	config.set_value("equiper", "bouclier_3", items_equiper.bouclier3)
	config.set_value("equiper", "bouclier_4", items_equiper.bouclier4)
	config.set_value("equiper", "bouclier_5", items_equiper.bouclier5)
	config.set_value("equiper", "bouclier_6", items_equiper.bouclier6)
	config.set_value("equiper", "bouclier_7", items_equiper.bouclier7)
	config.set_value("equiper", "casque_1", items_equiper.casque1)
	config.set_value("equiper", "casque_2", items_equiper.casque2)
	config.set_value("equiper", "casque_3", items_equiper.casque3)
	config.set_value("equiper", "casque_4", items_equiper.casque4)
	config.set_value("equiper", "casque_5", items_equiper.casque5)
	config.set_value("equiper", "casque_6", items_equiper.casque6)
	config.set_value("equiper", "collier_1", items_equiper.collier1)
	config.set_value("equiper", "collier_2", items_equiper.collier2)
	config.set_value("equiper", "collier_3", items_equiper.collier3)
	config.set_value("equiper", "heaume_1", items_equiper.heaume1)
	config.set_value("equiper", "heaume_2", items_equiper.heaume2)
	config.set_value("equiper", "heaume_3", items_equiper.heaume3)
	config.set_value("equiper", "heaume_4", items_equiper.heaume4)
	config.set_value("equiper", "heaume_5", items_equiper.heaume5)
	config.set_value("equiper", "heaume_6", items_equiper.heaume6)
	config.set_value("equiper", "sword_1", items_equiper.sword1)
	config.set_value("equiper", "sword_2", items_equiper.sword2)
	config.set_value("equiper", "sword_3", items_equiper.sword3)
	config.set_value("equiper", "sword_4", items_equiper.sword4)
	config.set_value("equiper", "sword_5", items_equiper.sword5)
	config.set_value("equiper", "sword_6", items_equiper.sword6)
	config.set_value("equiper", "sword_7", items_equiper.sword7)
	config.set_value("equiper", "sword_8", items_equiper.sword8)
	config.set_value("stat_bonus", "vie", addStatVie)
	config.set_value("stat_bonus", "mana", addStatMana)
	config.set_value("stat_bonus", "puissance", addStatPuissance)
	config.set_value("stat_bonus", "endurance", addStatEndurance)
	config.set_value("stat_bonus", "regene_endurance", addStatRegeneEndurance)
	config.set_value("stat_bonus", "attaque", addStatAttaque)
	config.set_value("stat_bonus", "defense", addStatDefense)
	
	config.save(SAVE_PATH)

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	pass
